steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-west1-docker.pkg.dev/projectcolorchef/project-colorchef/colorchef', '.' ]
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-west1-docker.pkg.dev/projectcolorchef/project-colorchef/colorchef']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'colorchef', 
        '--image', 'us-west1-docker.pkg.dev/projectcolorchef/project-colorchef/colorchef', 
        '--region', 'us-west1', '--platform', 'managed',
        '--allow-unauthenticated']
artifacts:
  objects:
    location: 'gs://colorchef-bucket'
    paths: ['*']
images:
- 'us-west1-docker.pkg.dev/projectcolorchef/project-colorchef/colorchef'